# - dataset: cuhk03
#   mode: lift
#   logs_dir: logs.tri.lift


- dataset: cuhk03
 mode: all
 logs_dir: logs.tri.all


- dataset: cuhk03/combine
 logs_dir: logs.again

- dataset: cuhk03/label
 arch: resnet101
 batch_size: 100
 logs_dir: logs.resnet101

- dataset: dukemtmc
 logs_dir: logs.dukemtmc.randeval

- dataset: cuhk03/label
 logs_dir: logs.cuhk03.label
- dataset: cuhk03/detect
 logs_dir: logs.cuhk03.detect
- dataset: cuhk03/combine
 logs_dir: logs.cuhk03.combine
- dataset: viper
 logs_dir: logs.viper
- dataset: cuhk01
 logs_dir: logs.cuhk01

- dataset: market1501
 logs_dir: logs.market1501.randeval

- dataset: cuhk03/combine
 seed: 1
 logs_dir: logs.seed1

# - dataset: cuhk03
#   logs_dir: logs.resnet152
#   dropout: 0
#   features: 1024
#   normalize: False
#   num_classes: 128
#   batch_size: 300
#   gpu: [1,2]
#
# - dataset: cuhk03
#   arch: resnet50
#   dropout: 0
#   features: 1024
#   normalize: False
#   num_classes: 128
#   logs_dir: logs.bs320
#   batch_size: 320
#   gpu: [1,2]

# - dataset: cuhk03
#   logs_dir: logs.bs480
#   batch_size: 480
#   gpu: [0,1,2]

# - arch: resnet50
#   dropout: 0
#   features: 1024
#   normalize: False
#   num_classes: 128
#   lr: 0.1
#   steps: [100,150,180]
#   epochs: 200
#   logs_dir: logs.res.0.sgd
#   gpu: [1,]

# - arch: resnet50
#   dropout: 0.3
#   logs_dir: logs.res.0.3

# - arch: attention50
#   gpu: [0,]
#   branchs: 8
#   branch_dim: 64
#   dropout: 0.3
#   freeze: False
#   use_global: False
#   normalize: True
#   logs_dir: logs.at.8.64.0.3

# - arch: attention50
#   branchs: 8
#   branch_dim: 128
#   dropout: 0.3
#   logs_dir: logs.at.8.128.0.3

# - dataset: cuhk03
#   arch: attention50
#   logs_dir: logs.at.dp.0.3
#
# - arch: attention50
#   branchs: 8
#   branch_dim: 64
#   dropout: 0.8
#   logs_dir: logs.at.0.8
